### ISSUE TITLE
Installing noise

### ISSUE THREAD

**Issue by cormullion** [NaN-xyz/Glyph-Filters#37]
I did the install for `noise`

```
% pip install noise
Collecting noise
  Downloading https://files.pythonhosted.org/packages/18/29/bb830ee6d934311e17a7a4fa1368faf3e73fbb09c0d80fc44e41828df177/noise-1.2.2.tar.gz (125kB)
     |████████████████████████████████| 133kB 4.7MB/s 
Installing collected packages: noise
  Running setup.py install for noise ... done
Successfully installed noise-1.2.2
```

 But it doesn't get recognised by the filter code:

```
Start
Traceback (most recent call last):
  File "MarkerHatch.py", line 8, in <module>
    from NaNGFGraphikshared import *
  File "NaNGFGraphikshared.py", line 13, in <module>
    from NaNGFNoise import roughenLines
  File "NaNGFNoise.py", line 2, in <module>
    from noise import *
ImportError: No module named noise
End
```

Is it some Python path thing perhaps? Not sure where these modules live...

(Glyphs Version 2.6.6 (1351))

**Comment by NaN-xyz** [comment]
Hi there. According to terminal mine is here: `Location: /Library/Python/2.7/site-packages`. I'm running v1.2.1 but it shouldn't matter.

Glyphs 2.x requires Python 2 so perhaps you've installed it to 3.x?

A workaround I've had in the past: On launching the app type `import noise' in to the macro window, and run. This seemed to do the import. Then try running one of the scripts.

**Comment by cormullion** [comment]
Oh yes I think I'm running Python 3.7... I'll investigate...

**Comment by cormullion** [comment]
This worked:

```
 python2 /Users/me/Library/Python/2.7/lib/python/site-packages/pip install noise
```

Thanks!

**Comment by NaN-xyz** [comment]
That's good to hear. Hope you have some fun with it.
